# Generated by Django 3.2.16 on 2022-10-16 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, verbose_name='Текст')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('type', models.CharField(choices=[('radio', 'Один правильный ответ'), ('checkbox', 'Несколько правильных ответов'), ('text', 'Текстовый ответ')], max_length=50, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('description', models.TextField(blank=True, default='Информации о тесте нет', null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, unique=True, verbose_name='Ссылка')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт для прохождения')),
                ('subtract_incorrect', models.BooleanField(default=True, verbose_name='Вычитать баллы за лишние варианты')),
                ('access', models.CharField(choices=[('all', 'Доступ для всех'), ('slug', 'Доступ только по ссылке')], default='all', max_length=50, verbose_name='Доступ')),
                ('attempts', models.IntegerField(choices=[(0, 'Не ограничено'), (1, 'Одна попытка'), (2, 'Две попытки'), (3, 'Три попытки')], default=0, verbose_name='Количество попыток')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('timelimit', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(10800)], verbose_name='Ограничение по времени')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='Текст')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.DateTimeField(auto_now_add=True, verbose_name='дата прохождения')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True, verbose_name='ссылка на результат')),
                ('result', models.IntegerField(verbose_name='набранный балл')),
                ('max_result', models.IntegerField(verbose_name='максимальный балл')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='quizes.quiz', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_results', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
                'ordering': ['passed'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizes.quiz', verbose_name='Тест'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique name of test by one author'),
        ),
    ]
