# Generated by Django 3.2.16 on 2022-10-12 21:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, verbose_name='текст')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('type', models.CharField(choices=[('radio', 'Один правильный ответ'), ('checkbox', 'Несколько правильных ответов')], max_length=50)),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='текст')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант',
                'verbose_name_plural': 'варианты',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('description', models.TextField(blank=True, default='Информации о тесте нет', null=True, verbose_name='описание')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, unique=True, verbose_name='ссылка')),
                ('access', models.CharField(choices=[('all', 'Доступ для всех'), ('slug', 'Доступ только по ссылке')], max_length=50, verbose_name='доступ')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыт для прохождения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('timelimit', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(10800)], verbose_name='ограничение по времени')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.DateTimeField(auto_now_add=True, verbose_name='дата прохождения')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True, verbose_name='ссылка на результат')),
                ('result', models.IntegerField(verbose_name='набранный балл')),
                ('max_result', models.IntegerField(verbose_name='максимальный балл')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='tests.test', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_results', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
                'ordering': ['passed'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='тест'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique name of test by one author'),
        ),
    ]
