# Generated by Django 3.2.16 on 2022-10-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprintquestion',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='blueprinttest',
            options={'ordering': ['created'], 'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'ответ на вопрос', 'verbose_name_plural': 'ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['passed'], 'verbose_name': 'результат', 'verbose_name_plural': 'результаты'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'вариант', 'verbose_name_plural': 'варианты'},
        ),
        migrations.AlterField(
            model_name='blueprintquestion',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blueprintquestion',
            name='type',
            field=models.CharField(choices=[('radio', 'Один правильный ответ'), ('checkbox', 'Несколько правильных ответов')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blueprinttest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blueprinttest',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
