# Generated by Django 3.2.16 on 2022-10-13 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.CharField(choices=[(0, 'Не ограничено'), (1, 'Одна попытка'), (2, 'Две попытки')], default=0, max_length=100, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='question',
            name='additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='test',
            name='access',
            field=models.CharField(choices=[('all', 'Доступ для всех'), ('slug', 'Доступ только по ссылке')], max_length=50, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, default='Информации о тесте нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт для прохождения'),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='test',
            name='timelimit',
            field=models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(10800)], verbose_name='Ограничение по времени'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Текст'),
        ),
    ]
