# Generated by Django 3.2.16 on 2022-10-09 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20221009_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprintquestion',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='blueprinttest',
            name='timelimit',
            field=models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(10800)]),
        ),
    ]
