# Generated by Django 3.2.16 on 2022-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20221013_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='access',
            field=models.CharField(choices=[('all', 'Доступ для всех'), ('slug', 'Доступ только по ссылке')], default='all', max_length=50, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(choices=[(0, 'Не ограничено'), (1, 'Одна попытка'), (2, 'Две попытки')], default=0, max_length=100, verbose_name='Количество попыток'),
        ),
    ]
