# Generated by Django 3.2.16 on 2022-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20221013_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subtract_incorrect',
            field=models.BooleanField(default=True, verbose_name='Вычитать баллы за лишние варианты'),
        ),
        migrations.AlterField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(choices=[(0, 'Не ограничено'), (1, 'Одна попытка'), (2, 'Две попытки'), (3, 'Три попытки')], default=0, max_length=100, verbose_name='Количество попыток'),
        ),
    ]
