# Generated by Django 3.2.16 on 2022-10-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20221010_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprintquestion',
            name='max_score',
        ),
        migrations.AddField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.blueprinttest', verbose_name='вопросы'),
        ),
    ]
