# Generated by Django 3.2.16 on 2022-10-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20221012_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.blueprinttest', verbose_name='вопросы'),
        ),
    ]
