# Generated by Django 3.2.16 on 2022-10-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20221013_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='variants',
        ),
    ]
