# Generated by Django 3.2.16 on 2022-10-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_question_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
