# Generated by Django 3.2.16 on 2022-10-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_variant_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='test',
        ),
    ]
